import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

import { Raleway , Oswald } from "next/font/google"

const Raleway_init = Raleway ({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--Raleway '
})

const Oswald_init = Oswald({
  subsets: ['latin'],
  weight: ['300', '400'],
  variable: "--Oswald",
})

export const metadata: Metadata = {
  title: "Avant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Oswald_init.variable} ${Raleway_init.variable} antialiased bg-[#f3f3f3]`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
